# Generated by Django 5.1.4 on 2024-12-12 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='booking.station')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='booking.station')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_no', models.IntegerField()),
                ('train_name', models.CharField(max_length=100)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='booking.route')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_schedules', to='booking.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.CharField(max_length=10)),
                ('class_type', models.CharField(max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.train')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.train'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('booking_status', models.BooleanField()),
                ('booking_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.schedule')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.train')),
            ],
        ),
    ]
