# Generated by Django 5.1.4 on 2024-12-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_schedule_train_alter_seat_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='train',
        ),
    ]
