# Generated by Django 5.1.4 on 2024-12-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_name_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking.seat'),
        ),
    ]
