# Generated by Django 5.1.4 on 2024-12-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_seat_amount_alter_booking_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='availability',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='train_id',
            new_name='train',
        ),
        migrations.AddField(
            model_name='booking',
            name='class_type',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='class_type',
            field=models.IntegerField(default=3),
        ),
    ]
