# Generated by Django 5.1.4 on 2024-12-19 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_schedule_id_booking_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='WAITLISTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='class_type',
            field=models.IntegerField(),
        ),
    ]
