# Generated by Django 5.1.4 on 2024-12-27 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_bookings', to='booking.station'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_bookings', to='booking.station'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
