# Generated by Django 5.1.4 on 2024-12-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_train_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
