# Generated by Django 5.1.4 on 2025-01-02 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_routestop_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='departue_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
