# Generated by Django 5.1.4 on 2025-01-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_routestop_departue_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routestop',
            old_name='departue_time',
            new_name='departure_time',
        ),
    ]
